### ISSUE TITLE
beer.js na Semana da Computação UFSCar Sorocaba

### ISSUE THREAD

**Issue by andrebnf** [beerjs/sorocaba#2]
## Sugestões
Ideia levantada no [Gitter](https://gitter.im/beerjs/sorocaba) por @brenolf e @mccraveiro de fazermos nosso primeiro encontro durante a Semana da Computação na UFSCar Sorocaba
**Data:** de 11 à 14 de Maio (dia do encontro não definido)

**Clécio Bachini** estará no evento e estamos aguardando a confirmação dele.

Precisamos de um planejamento pro encontro. Ideias?

**Comment by eiguike** [comment]
Poderíamos utilizar um laboratório como espaço desse encontro, porquê teriamos internet garantida e um projetor maneiro; só seria maneiro alguém trouxesse um roteador, porquê não é garantido que o do laboratório funcione...

Em questão da utilização do espaço, poderiamos deixar aberto o projetor com os trabalhos do pessoal... Ou então, um coding dojo pra tentar replicar o trabalho da pessoa que queira mostrar... :p

**Comment by andrebnf** [comment]
Estamos tentando conseguir um laboratório, mesmo pq queremos ter algum workshop na Semana. O problema é que tá difícil conseguir hahah. Mas vou mantendo vcs atualizados

**Comment by brenolf** [comment]
@eiguike Agora que percebi um ponto super legal que a internet. Mas como falei no gitter, sei lá o que é mais legal: keynote ou dojo. Dá pra fazer os dois, mas isso depende do tempo que a gente vai ter. Dava pra fazer o keynote com um tempo alocado e o dojo em paralelo com outro evento (sei lá) aí não travaria nada, o que acham?

**Comment by mccraveiro** [comment]
Acho que podíamos fazer uma palestra/workshop sobre ES6. Mais fácil para quem está aprendendo JS agora.

**Comment by brenolf** [comment]
O Clécio tem alguma ideia do que vai querer falar no beer?
